version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_bot
    env_file: .env
    environment:
      TZ: 'Asia/Tokyo'
    tty: true
    ports:
      - 23000:${PORT}
    volumes:
      - type: bind
        source: .
        target: /app
